apiVersion: v1
kind: Service
metadata:
  name: lt-service
spec:
  type: NodePort
  ports:
    - targetPort: 8010 # port on the pod
      port: 8081 # port on the service
      nodePort: 30080 # port on the node
  selector:
    app: languagetool
